# Generated by Django 6.0.6 on 2026-06-23 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('reference', models.CharField(default=None, max_length=255, verbose_name='Reference')),
                ('vendor', models.CharField(default=None, max_length=255, verbose_name='Vendor')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Description')),
                ('order_date', models.DateField(blank=True, default=None, null=True, verbose_name='Order Date')),
                ('expected_date', models.DateField(blank=True, default=None, null=True, verbose_name='Expected Date')),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='draft', max_length=100, null=True, verbose_name='Status')),
                ('category', models.CharField(blank=True, choices=[('Raw Material', 'Raw Material'), ('Finished Good', 'Finished Good'), ('Service', 'Service'), ('Asset', 'Asset')], default=None, max_length=100, null=True, verbose_name='Category')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Total')),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default=None, max_length=100, null=True, verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
            },
        ),
    ]
