# Generated by Django 6.0.6 on 2026-06-25 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('reference', models.CharField(default=None, max_length=255, verbose_name='Reference')),
                ('receipt_date', models.DateField(blank=True, default=None, null=True, verbose_name='Receipt Date')),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('waiting', 'Waiting'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='draft', max_length=100, null=True, verbose_name='Status')),
                ('warehouse', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Warehouse')),
                ('notes', models.TextField(blank=True, default=None, null=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('purchase_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.goodsreceipt', verbose_name='Purchase Order')),
            ],
            options={
                'verbose_name': 'Goods Receipt',
                'verbose_name_plural': 'Goods Receipts',
            },
        ),
    ]
