# Generated by Django 6.0.6 on 2026-06-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_purchaseorder_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='sales',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Sales'),
        ),
    ]
