# Generated by Django 6.0.6 on 2026-06-26 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_customer_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='reference',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Reference'),
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Name')),
                ('code', models.CharField(default=None, help_text='Unique identifier, e.g. "purchase.order.local"', max_length=255, verbose_name='Code')),
                ('prefix', models.CharField(blank=True, default='%(year)s/', help_text='Support formats: %(year)s, %(y)s, %(month)s, %(day)s', max_length=255, null=True, verbose_name='Prefix')),
                ('suffix', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Suffix')),
                ('padding', models.IntegerField(blank=True, default=3, null=True, verbose_name='Padding')),
                ('reset_period', models.CharField(blank=True, choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('no_reset', 'No Reset')], default='yearly', help_text='When to reset counter: yearly / monthly / never', max_length=100, null=True, verbose_name='Reset Period')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Sequence',
                'verbose_name_plural': 'Sequences',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sequence_id',
            field=models.ForeignKey(blank=True, help_text='Pilih format nomor dokumen (PO Local / PO Import, dll)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sequence', verbose_name='Sequence'),
        ),
        migrations.CreateModel(
            name='SequenceDateRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_from', models.DateField(default=None, verbose_name='Date From')),
                ('date_to', models.DateField(blank=True, default=None, null=True, verbose_name='Date To')),
                ('number_next', models.IntegerField(blank=True, default=1, null=True, verbose_name='Next Number')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('sequence_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sequence', verbose_name='Sequence')),
            ],
            options={
                'verbose_name': 'Sequence Date Range',
                'verbose_name_plural': 'Sequence Date Ranges',
            },
        ),
    ]
