# Generated by Django 6.0.6 on 2026-06-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_purchaseorder_reference_sequence_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='goodsreceipt',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Goods Receipt', 'verbose_name_plural': 'Goods Receipts'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Purchase Order', 'verbose_name_plural': 'Purchase Orders'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderline',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Purchase Order Line', 'verbose_name_plural': 'Purchase Order Lines'},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Sales Order', 'verbose_name_plural': 'Sales Orders'},
        ),
        migrations.AlterModelOptions(
            name='salesorderline',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Sales Order Line', 'verbose_name_plural': 'Sales Order Lines'},
        ),
        migrations.AlterModelOptions(
            name='sequence',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Sequence', 'verbose_name_plural': 'Sequences'},
        ),
        migrations.AlterModelOptions(
            name='sequencedaterange',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Sequence Date Range', 'verbose_name_plural': 'Sequence Date Ranges'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
        migrations.AddField(
            model_name='sequence',
            name='model_ref',
            field=models.CharField(blank=True, default=None, help_text='Model yg menggunakan sequence ini, e.g. "purchase.order"', max_length=255, null=True, verbose_name='Document Type'),
        ),
    ]
