# Generated by Django 6.0.6 on 2026-06-26 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_customer_options_alter_goodsreceipt_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Product Name')),
                ('code', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='SKU / Code')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Description')),
                ('category', models.CharField(blank=True, choices=[('Raw Material', 'Raw Material'), ('Finished Good', 'Finished Good'), ('Service', 'Service'), ('Asset', 'Asset')], default=None, max_length=100, null=True, verbose_name='Category')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Sales Price')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Cost')),
                ('uom', models.CharField(blank=True, default='pcs', max_length=255, null=True, verbose_name='Unit of Measure')),
                ('weight', models.FloatField(blank=True, default=None, null=True, verbose_name='Weight (kg)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
