# Generated by Django 6.0.6 on 2026-06-26 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderline',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.product', verbose_name='Product'),
        ),
    ]
