# Generated by Django 6.0.6 on 2026-06-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_purchaseorderline_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('record_id', models.IntegerField(db_index=True)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'chatter_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'record_id'], name='chatter_log_model_n_b0220b_idx')],
            },
        ),
    ]
