# Generated by Django 6.0.6 on 2026-06-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_chatterlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='discount_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Discount (%)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Grand Total'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax_rate',
            field=models.FloatField(blank=True, default=11, null=True, verbose_name='Tax (%)'),
        ),
    ]
