# Generated by Django 6.0.6 on 2026-06-28 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_purchaseorder_discount_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Grand Total'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='promo_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Promo (%)'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tax_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Tax (%)'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.product', verbose_name='Product'),
        ),
    ]
