# Generated by Django 6.0.6 on 2026-06-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_salesorder_grand_total_salesorder_promo_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Phone'),
        ),
    ]
