# Generated by Django 6.0.6 on 2026-06-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_customer_status_customer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Alamat Vendor'),
        ),
    ]
