# Generated by Django 6.0.6 on 2026-06-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_vendor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Alamat Vendor'),
        ),
    ]
