# Generated by Django 6.0.6 on 2026-06-30 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_vendor_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.TextField(blank=True, default=None, null=True, verbose_name='Description')),
                ('order_qty', models.FloatField(blank=True, default=0, null=True, verbose_name='Order Qty')),
                ('received_qty', models.FloatField(blank=True, default=0, null=True, verbose_name='Received Qty')),
                ('pending_qty', models.FloatField(blank=True, default=0, null=True, verbose_name='Pending Qty')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Unit Price')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.product', verbose_name='Product')),
                ('receipt_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.goodsreceipt', verbose_name='Goods Receipt')),
            ],
            options={
                'verbose_name': 'Goods Receipt Line',
                'verbose_name_plural': 'Goods Receipt Lines',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
