# Generated by Django 6.0.6 on 2026-06-30 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_goodsreceiptline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('reference', models.CharField(default=None, max_length=255, verbose_name='Reference')),
                ('delivery_date', models.DateField(blank=True, default=None, null=True, verbose_name='Delivery Date')),
                ('warehouse', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Warehouse')),
                ('address', models.TextField(blank=True, default=None, null=True, verbose_name='Delivery Address')),
                ('notes', models.TextField(blank=True, default=None, null=True, verbose_name='Notes')),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('waiting', 'Waiting'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='draft', max_length=100, null=True, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customer', verbose_name='Customer')),
                ('sales_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.salesorder', verbose_name='Sales Order')),
            ],
            options={
                'verbose_name': 'Delivery Order',
                'verbose_name_plural': 'Delivery Orders',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.TextField(blank=True, default=None, null=True, verbose_name='Description')),
                ('order_qty', models.FloatField(blank=True, default=0, null=True, verbose_name='Order Qty')),
                ('delivered_qty', models.FloatField(blank=True, default=0, null=True, verbose_name='Delivered Qty')),
                ('pending_qty', models.FloatField(blank=True, default=0, null=True, verbose_name='Pending Qty')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Unit Price')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('delivery_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.deliveryorder', verbose_name='Delivery Order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Delivery Order Line',
                'verbose_name_plural': 'Delivery Order Lines',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
