# Generated by Django 6.0.6 on 2026-07-02 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Company Name')),
                ('code', models.CharField(default=None, help_text='Unique short code, e.g. PTABC', max_length=255, verbose_name='Code')),
                ('address', models.TextField(blank=True, default=None, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Phone')),
                ('email', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Email')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Branch Name')),
                ('code', models.CharField(default=None, help_text='Short identifier, e.g. HQ, GDG1', max_length=255, verbose_name='Code')),
                ('address', models.TextField(blank=True, default=None, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Phone')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
