# Generated by Django 6.0.6 on 2026-07-04 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_company_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('code', models.CharField(default=None, help_text='Format: 1-1000, 1-2000, dst.', max_length=255, verbose_name='Kode Akun')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Nama Akun')),
                ('type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], default=None, max_length=100, verbose_name='Tipe Akun')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent', models.ForeignKey(blank=True, help_text='Akun induk untuk struktur hierarki', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.chartofaccount', verbose_name='Parent Akun')),
            ],
            options={
                'verbose_name': 'Chart of Account',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jurnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('reference', models.CharField(default=None, help_text='Nomor referensi jurnal', max_length=255, verbose_name='Reference')),
                ('date', models.DateField(default=None, verbose_name='Tanggal Jurnal')),
                ('description', models.TextField(blank=True, default=None, help_text='Keterangan transaksi jurnal', null=True, verbose_name='Deskripsi')),
                ('journal_type', models.CharField(choices=[('general', 'General Journal'), ('sales', 'Sales Journal'), ('purchase', 'Purchase Journal'), ('cash', 'Cash Journal')], default=None, max_length=100, verbose_name='Tipe Jurnal')),
                ('total_debit', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Total Debit')),
                ('total_credit', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Total Credit')),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=100, null=True, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Jurnal',
                'verbose_name_plural': 'Jurnal',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JurnalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('debit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Debit')),
                ('credit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Credit')),
                ('description', models.CharField(blank=True, default=None, help_text='Keterangan baris jurnal', max_length=255, null=True, verbose_name='Deskripsi')),
                ('account', models.ForeignKey(help_text='Akun debit/credit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.chartofaccount', verbose_name='Akun')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('jurnal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.jurnal', verbose_name='Jurnal')),
            ],
            options={
                'verbose_name': 'Jurnal Line',
                'verbose_name_plural': 'Jurnal Lines',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
