# Generated by Django 6.0.6 on 2026-07-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_chartofaccount_jurnal_jurnalline'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='discount_percentage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Disc (%)'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='tax_percentage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Tax (%)'),
        ),
    ]
