# Generated by Django 6.0.6 on 2026-07-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_purchaseorderline_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='manual_discount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Manual Disc (%)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Tax'),
        ),
    ]
