# Generated by Django 6.0.6 on 2026-07-04 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_branch_updated_by_chartofaccount_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=150, verbose_name='Username')),
                ('email', models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Last Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser')),
                ('date_joined', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last Login')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('code', models.CharField(default=None, max_length=255, verbose_name='Kode Gudang')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Nama Gudang')),
                ('address', models.TextField(blank=True, default=None, null=True, verbose_name='Alamat')),
                ('phone', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Telepon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
