# Generated by Django 6.0.6 on 2026-07-04 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_vendorbill_vendorbillline'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbill',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.purchaseorder', verbose_name='Purchase Order'),
        ),
    ]
