# Generated by Django 6.0.6 on 2026-07-12 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_vendorbill_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbill',
            name='down_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Down Payment'),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='is_down_payment',
            field=models.BooleanField(default=False, verbose_name='DP Bill'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='sequence_id',
            field=models.ForeignKey(blank=True, help_text='Pilih format nomor dokumen (PO Local / PO Import, dll)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sequence', verbose_name='Order Type'),
        ),
    ]
