# Generated by Django 6.0.6 on 2026-07-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_customerinvoice_customerinvoiceline'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='discount_method',
            field=models.CharField(blank=True, choices=[('percentage', 'Discount (%)'), ('nominal', 'Discount (Rp)')], default='percentage', max_length=100, null=True, verbose_name='Metode Diskon'),
        ),
    ]
