# Generated by Django 6.0.6 on 2026-07-18 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_purchaseorder_discount_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorderline',
            name='order_qty',
        ),
        migrations.RemoveField(
            model_name='deliveryorderline',
            name='pending_qty',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptline',
            name='order_qty',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptline',
            name='pending_qty',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sequence_id',
            field=models.ForeignKey(blank=True, help_text='Pilih format nomor dokumen (SO Local / SO Online, dll)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sequence', verbose_name='Order Type'),
        ),
        migrations.AlterField(
            model_name='customerinvoiceline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='reference',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='vendorbillline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.product', verbose_name='Product'),
        ),
    ]
