# Generated by Django 6.0.6 on 2026-07-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_deliveryorderline_order_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='total',
        ),
    ]
