# Generated by Django 6.0.6 on 2026-07-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_purchaseorder_total_remove_salesorder_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='promo_rate',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='discount_method',
            field=models.CharField(blank=True, choices=[('percentage', 'Discount (%)'), ('nominal', 'Discount (Rp)')], default='percentage', max_length=100, null=True, verbose_name='Metode Diskon'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='manual_discount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Manual Disc (%)'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='discount_percentage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Disc (%)'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='tax_percentage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Tax (%)'),
        ),
    ]
