# Generated by Django 6.0.6 on 2026-07-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_salesorder_promo_rate_salesorder_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Amount Due'),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Amount Due'),
        ),
    ]
