# Generated by Django 6.0.6 on 2026-07-19 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_customerinvoice_due_amount_vendorbill_due_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinvoice',
            name='due_amount',
        ),
        migrations.RemoveField(
            model_name='vendorbill',
            name='due_amount',
        ),
    ]
