# Generated by Django 6.0.6 on 2026-07-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_customerinvoice_due_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoice',
            name='reference',
            field=models.CharField(default=None, max_length=255, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='reference',
            field=models.CharField(default=None, max_length=255, verbose_name='Reference'),
        ),
    ]
