# Generated by Django 6.0.6 on 2026-07-19 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_customerinvoice_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='sequence_id',
            field=models.ForeignKey(blank=True, help_text='Pilih format nomor dokumen pengiriman barang', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sequence', verbose_name='Sequence'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='sequence_id',
            field=models.ForeignKey(blank=True, help_text='Pilih format nomor dokumen penerimaan barang', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sequence', verbose_name='Sequence'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='reference',
            field=models.CharField(default=None, max_length=255, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='reference',
            field=models.CharField(default=None, max_length=255, verbose_name='Reference'),
        ),
    ]
