# Generated by Django 6.0.6 on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_deliveryorder_sequence_id_goodsreceipt_sequence_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='bill_method',
            field=models.CharField(blank=True, choices=[('on_order', 'On Order'), ('on_receipt', 'On Receipt')], default='on_order', max_length=100, verbose_name='Metode Tagihan'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='bill_method',
            field=models.CharField(blank=True, choices=[('on_order', 'On Order'), ('on_receipt', 'On Receipt')], default=None, max_length=100, null=True, verbose_name='Metode Tagihan'),
        ),
    ]
