# Generated by Django 6.0.6 on 2026-07-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_vendor_bill_method_purchaseorder_bill_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='manual_discount',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('per_product', 'Per Product'), ('global', 'Global'), ('combined', 'Gabungan')], default='per_product', max_length=100, null=True, verbose_name='Tipe Diskon'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='global_discount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Global Discount'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='bill_method',
            field=models.CharField(blank=True, choices=[('on_order', 'On Order'), ('on_receipt', 'On Receipt')], default=None, help_text='Default mengikuti setting Vendor', max_length=100, null=True, verbose_name='Metode Tagihan'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='bill_method',
            field=models.CharField(blank=True, choices=[('on_order', 'On Order'), ('on_receipt', 'On Receipt')], default='on_order', max_length=100, null=True, verbose_name='Metode Tagihan'),
        ),
    ]
