# Generated by Django 6.0.6 on 2026-07-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_purchaseorder_manual_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='global_discount',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='global_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Global Disc (Rp)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='global_discount_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Global Disc (%)'),
        ),
    ]
