# Generated by Django 6.0.6 on 2026-07-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_purchaseorder_global_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='global_discount_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='global_discount_rate',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='global_discount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Global Discount'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('per_product', 'Per Product'), ('global', 'Global Discount')], default='per_product', max_length=100, null=True, verbose_name='Tipe Diskon'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='global_discount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Global Discount'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('per_product', 'Per Product'), ('global', 'Global Discount')], default='per_product', max_length=100, null=True, verbose_name='Tipe Diskon'),
        ),
    ]
