# Generated by Django 6.0.6 on 2026-07-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbill',
            name='due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Amount Due'),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Paid'),
        ),
    ]
