# Generated by Django 6.0.6 on 2026-07-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_vendorbill_due_amount_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbill',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=100, null=True, verbose_name='Payment Status'),
        ),
    ]
