# Generated by Django 6.0.6 on 2026-07-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_vendorpaymentline'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpayment',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Remaining Amount'),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='total_allocation',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Total Allocation'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Total Payment'),
        ),
        migrations.AlterField(
            model_name='vendorpaymentline',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=18, verbose_name='Payment Allocation'),
        ),
    ]
