# Generated by Django 6.0.6 on 2026-07-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_vendorpayment_remaining_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Amount Due'),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Paid'),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=100, null=True, verbose_name='Payment Status'),
        ),
    ]
