# Generated by Django 6.0.6 on 2026-07-27 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_customerinvoice_due_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('reference', models.CharField(default=None, max_length=255, verbose_name='Reference')),
                ('payment_date', models.DateField(default=None, verbose_name='Payment Date')),
                ('payment_ref', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Payment Reference')),
                ('currency', models.CharField(blank=True, default='IDR', max_length=255, null=True, verbose_name='Currency')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Total Receipt')),
                ('total_allocation', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Total Allocation')),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Remaining Amount')),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='draft', max_length=100, null=True, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customer', verbose_name='Customer')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.paymentmethod', verbose_name='Payment Method')),
                ('sequence_id', models.ForeignKey(blank=True, help_text='Pilih format nomor dokumen penerimaan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sequence', verbose_name='Sequence')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Customer Receipt',
                'verbose_name_plural': 'Customer Receipts',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('received_amount', models.DecimalField(decimal_places=2, default=None, max_digits=18, verbose_name='Received Amount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('invoice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customerinvoice', verbose_name='Invoice')),
                ('receipt_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customerreceipt', verbose_name='Customer Receipt')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Customer Receipt Line',
                'verbose_name_plural': 'Customer Receipt Lines',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
