# Generated by Django 6.0.6 on 2026-07-30 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_purchaserequest_purchaserequestline'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='sequence_id',
            field=models.ForeignKey(blank=True, help_text='Pilih format nomor dokumen (PR, dll)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sequence', verbose_name='Document Type'),
        ),
    ]
