# Generated by Django 6.0.6 on 2026-07-30 11:39

import django.db.models.deletion
from django.db import migrations, models


def clear_requested_by(apps, schema_editor):
    """Delete existing PR records (test data) before altering field type."""
    PurchaseRequest = apps.get_model('core', 'PurchaseRequest')
    PurchaseRequest.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_purchaserequest_sequence_id'),
    ]

    operations = [
        migrations.RunPython(clear_requested_by, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='purchaserequest',
            name='request_date',
            field=models.DateField(default=None, verbose_name='Request Date'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user', verbose_name='Requested By'),
        ),
    ]
