# Generated by Django 6.0.6 on 2026-07-30 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_purchaserequest_request_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequestline',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user', verbose_name='Requested By'),
        ),
    ]
