# Generated by Django 6.0.6 on 2026-07-30 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_remove_purchaserequestline_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.purchaserequest', verbose_name='Purchase Request'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='purchase_request_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.purchaserequestline', verbose_name='Purchase Request Line'),
        ),
    ]
