# Generated by Django 6.0.6 on 2026-07-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_purchaseorder_purchase_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='source_document',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Source Document'),
        ),
    ]
