# Generated by Django 6.0.6 on 2026-08-01 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_purchaseorder_source_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Nama Proyek')),
                ('category', models.CharField(blank=True, choices=[('konstruksi', 'Konstruksi'), ('infrastruktur', 'Infrastruktur'), ('interior', 'Interior'), ('renovasi', 'Renovasi'), ('lainnya', 'Lainnya')], default='konstruksi', max_length=100, null=True, verbose_name='Kategori')),
                ('date_start', models.DateField(blank=True, default=None, null=True, verbose_name='Tanggal Mulai')),
                ('date_end', models.DateField(blank=True, default=None, null=True, verbose_name='Tanggal Selesai')),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Nilai Kontrak')),
                ('location', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Lokasi')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customer', verbose_name='Client / Owner')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('executing_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.company', verbose_name='Entitas Pelaksana')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user', verbose_name='Manajer Proyek (PM)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
