# Generated by Django 6.0.6 on 2026-08-01 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(default=None, help_text='Misal: Kavling, Rumah Type A, Modul Sistem', max_length=255, verbose_name='Unit Produk')),
                ('specifications', models.TextField(blank=True, default=None, null=True, verbose_name='Spesifikasi')),
                ('quality_standard', models.TextField(blank=True, default=None, help_text='Checklist standar kualitas luaran', null=True, verbose_name='Standar Kualitas (Checkout List)')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Harga Jual Dasar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
