# Generated by Django 6.0.6 on 2026-08-01 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(default=None, help_text='Misal: PBG, Pemecahan Sertifikat, SHM, PPH Final 4%', max_length=255, verbose_name='Nama Dokumen')),
                ('doc_type', models.CharField(blank=True, choices=[('risk', 'Kategori Risiko'), ('license', 'Perizinan'), ('tax', 'Perpajakan')], default='license', max_length=100, null=True, verbose_name='Jenis Dokumen')),
                ('reference', models.CharField(blank=True, default=None, help_text='Misal: PP 16/2021, UU 28/2009', max_length=255, null=True, verbose_name='Dasar Hukum / Referensi')),
                ('rate', models.FloatField(blank=True, default=0, help_text='Tarif persen untuk aturan perpajakan (PPH, BPHTB, Pajak Konstruksi)', null=True, verbose_name='Tarif (%)')),
                ('validity_days', models.IntegerField(blank=True, default=None, help_text='Masa berlaku dokumen perizinan', null=True, verbose_name='Masa Berlaku (hari)')),
                ('description', models.TextField(blank=True, default=None, help_text='Standar kualitas, kewajiban, atau catatan legalitas', null=True, verbose_name='Keterangan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Dokumen',
                'verbose_name_plural': 'Dokumen',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
