# Generated by Django 6.0.6 on 2026-08-01 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_dokumen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('code', models.CharField(default=None, help_text='Kode standar, misal: MS-01, MS-02', max_length=255, verbose_name='Kode Milestone')),
                ('name', models.CharField(default=None, help_text='Misal: DP / Tanda Jadi, Pondasi, Struktur & Atap, Finishing, Retensi', max_length=255, verbose_name='Nama Milestone')),
                ('weight', models.FloatField(blank=True, default=0, help_text='Estimasi bobot persentase milestone (misal: Pondasi 25%, Struktur & Atap 30%)', null=True, verbose_name='Bobot (%)')),
                ('claim_requirements', models.TextField(blank=True, default=None, help_text='Syarat kelengkapan dokumen atau syarat klaim pembayaran milestone', null=True, verbose_name='Syarat Klaim / Kelengkapan Dokumen')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
