# Generated by Django 6.0.6 on 2026-08-01 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_project_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Kategori proyek dari master Project Categories', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.projectcategory', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(default=None, help_text='Misal: Konstruksi, Infrastruktur, Interior, Renovasi, Lainnya', max_length=255, verbose_name='Nama Kategori'),
        ),
    ]
