# Generated by Django 6.0.6 on 2026-08-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_projectcategory_updated_by_alter_project_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='code',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='weight',
        ),
    ]
