# Generated by Django 6.0.6 on 2026-08-01 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_remove_milestone_code_remove_milestone_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('type', models.CharField(blank=True, default=None, help_text='Tipe aktivitas (bebas), misal: Persiapan, Struktur, Dokumen', max_length=255, null=True, verbose_name='Type')),
                ('name', models.CharField(default=None, help_text='Nama aktivitas yang harus diselesaikan', max_length=255, verbose_name='Aktivitas')),
                ('weight', models.FloatField(blank=True, default=0, help_text='Bobot aktivitas terhadap milestone', null=True, verbose_name='Bobot (%)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('milestone_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.milestone', verbose_name='Milestone')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Milestone Line',
                'verbose_name_plural': 'Milestone Lines',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
