# Generated by Django 6.0.6 on 2026-08-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_projectline'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectline',
            name='progress',
            field=models.FloatField(blank=True, default=0, help_text='Progress pengerjaan milestone (0–100%)', null=True, verbose_name='Progress (%)'),
        ),
    ]
