# Generated by Django 6.0.6 on 2026-08-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_projectunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectunit',
            name='qty_available',
            field=models.IntegerField(blank=True, default=0, help_text='Jumlah unit yang tersedia untuk dijual', null=True, verbose_name='Unit Tersedia'),
        ),
        migrations.AddField(
            model_name='projectunit',
            name='qty_sold',
            field=models.IntegerField(blank=True, default=0, help_text='Jumlah unit yang sudah terjual', null=True, verbose_name='Unit Terjual'),
        ),
        migrations.AddField(
            model_name='projectunit',
            name='sold_percentage',
            field=models.FloatField(blank=True, default=0, help_text='Persentase terjual dari unit tersedia (otomatis)', null=True, verbose_name='% Terjual'),
        ),
    ]
