# Generated by Django 6.0.6 on 2026-08-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_vendorbill_project_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorbill',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='draft', max_length=100, null=True, verbose_name='Status'),
        ),
    ]
