# Generated by Django 6.0.6 on 2026-08-03 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_expense_expenseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.paymentmethod', verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='expense',
            name='reference',
            field=models.CharField(default=None, max_length=255, verbose_name='Reference'),
        ),
        migrations.AddField(
            model_name='expense',
            name='sequence_id',
            field=models.ForeignKey(blank=True, help_text='Pilih format nomor dokumen input biaya', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sequence', verbose_name='Sequence'),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('posted', 'Posted')], default='draft', max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='expenseline',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Wajib diisi saat POST', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.chartofaccount', verbose_name='Account'),
        ),
    ]
