# Generated by Django 6.0.6 on 2026-08-03 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_expense_payment_method_expense_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='project_line',
            field=models.ForeignKey(blank=True, help_text='Milestone terkait (otomatis dari wizard Input Expenses)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.projectline', verbose_name='Milestone'),
        ),
    ]
