# Generated by Django 6.0.6 on 2026-08-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_projectunitdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectunitdetail',
            name='est_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Est. Biaya Konstruksi'),
        ),
        migrations.AddField(
            model_name='projectunitdetail',
            name='est_margin',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Est. Margin'),
        ),
        migrations.AddField(
            model_name='projectunitdetail',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Harga Jual'),
        ),
    ]
