# Generated by Django 6.0.6 on 2026-08-09 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_projectunitdetail_est_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitDetailPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(default=None, help_text='Misal: DP, Termin 1, Termin 2, Pelunasan', max_length=255, verbose_name='Pembayaran')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Jumlah')),
                ('payment_date', models.DateField(blank=True, default=None, null=True, verbose_name='Tanggal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('unit_detail_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.projectunitdetail', verbose_name='Unit Detail')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Unit Detail Payment',
                'verbose_name_plural': 'Unit Detail Payments',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitDetailProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(default=None, help_text='Misal: Termin 1, Termin 2, Finishing', max_length=255, verbose_name='Tahap')),
                ('progress', models.FloatField(blank=True, default=0, null=True, verbose_name='Progress (%)')),
                ('date', models.DateField(blank=True, default=None, null=True, verbose_name='Tanggal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('unit_detail_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.projectunitdetail', verbose_name='Unit Detail')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Unit Detail Progress',
                'verbose_name_plural': 'Unit Detail Progress',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
