# Generated by Django 6.0.6 on 2026-08-15 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='milestone_line',
            field=models.ForeignKey(blank=True, help_text='Sub-line milestone terkait (dari wizard Input Expenses)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.milestoneline', verbose_name='Milestone Line'),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='milestone_line',
            field=models.ForeignKey(blank=True, help_text='Sub-line milestone terkait (dari wizard Buat Tagihan)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.milestoneline', verbose_name='Milestone Line'),
        ),
    ]
