# Generated by Django 6.0.6 on 2026-08-24 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_expense_milestone_line_vendorbill_milestone_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Milestone', 'verbose_name_plural': 'Milestone'},
        ),
        migrations.AlterModelOptions(
            name='milestoneline',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Baris Milestone', 'verbose_name_plural': 'Baris Milestone'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Project'},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Project Kategori', 'verbose_name_plural': 'Project Kategori'},
        ),
        migrations.AlterModelOptions(
            name='projectline',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Baris Proyek', 'verbose_name_plural': 'Baris Proyek'},
        ),
        migrations.AlterModelOptions(
            name='projectunit',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Unit Proyek', 'verbose_name_plural': 'Unit Proyek'},
        ),
        migrations.AlterModelOptions(
            name='projectunitdetail',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Detail Unit', 'verbose_name_plural': 'Detail Unit'},
        ),
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Permintaan Pembelian', 'verbose_name_plural': 'Permintaan Pembelian'},
        ),
        migrations.AlterModelOptions(
            name='purchaserequestline',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Baris Permintaan Pembelian', 'verbose_name_plural': 'Baris Permintaan Pembelian'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Unit', 'verbose_name_plural': 'Unit'},
        ),
        migrations.AlterModelOptions(
            name='unitdetailpayment',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Pembayaran Unit', 'verbose_name_plural': 'Pembayaran Unit'},
        ),
        migrations.AlterModelOptions(
            name='unitdetailprogress',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Progress Unit', 'verbose_name_plural': 'Progress Unit'},
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.purchaseorder', verbose_name='Purchase Order'),
        ),
        migrations.AlterField(
            model_name='milestoneline',
            name='type',
            field=models.CharField(blank=True, default=None, help_text='Tipe aktivitas (bebas), misal: Persiapan, Struktur, Dokumen', max_length=255, null=True, verbose_name='Tipe'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Kategori proyek dari master Project Kategori', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.projectcategory', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='bill_method',
            field=models.CharField(blank=True, choices=[('on_order', 'Saat Pesanan'), ('on_receipt', 'Saat Penerimaan')], default=None, help_text='Default mengikuti setting Vendor', max_length=100, null=True, verbose_name='Metode Tagihan'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='category',
            field=models.CharField(blank=True, choices=[('Bahan Baku', 'Bahan Baku'), ('Barang Jadi', 'Barang Jadi'), ('Jasa', 'Jasa'), ('Aset', 'Aset')], default=None, max_length=100, null=True, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Diskon'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='discount_method',
            field=models.CharField(blank=True, choices=[('percentage', 'Diskon (%)'), ('nominal', 'Diskon (Rp)')], default='percentage', max_length=100, null=True, verbose_name='Metode Diskon'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('per_product', 'Per Produk'), ('global', 'Diskon Global')], default='per_product', max_length=100, null=True, verbose_name='Tipe Diskon'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='expected_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Perkiraan Tanggal Terima'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='global_discount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Diskon Global'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Tanggal Pesanan'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi')], default=None, max_length=100, null=True, verbose_name='Prioritas'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.purchaserequest', verbose_name='Permintaan Pembelian'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='reference',
            field=models.CharField(default=None, max_length=255, verbose_name='Referensi'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='sequence_id',
            field=models.ForeignKey(blank=True, help_text='Pilih format nomor dokumen (PO Local / PO Import, dll)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sequence', verbose_name='Tipe Dokumen'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='source_document',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Dokumen Sumber'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Pajak'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Diskon'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='discount_percentage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Diskon (%)'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='name',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Harga Satuan'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.product', verbose_name='Produk'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='purchase_request_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.purchaserequestline', verbose_name='Baris Permintaan Pembelian'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='qty',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Jumlah'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Pajak'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='tax_percentage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Pajak (%)'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='estimated_receipt_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Deadline Barang Terima'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='reference',
            field=models.CharField(default=None, max_length=255, verbose_name='Referensi'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='request_date',
            field=models.DateField(default=None, verbose_name='Tanggal Permintaan'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user', verbose_name='Diminta Oleh'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='sequence_id',
            field=models.ForeignKey(blank=True, help_text='Pilih format nomor dokumen (PR, dll)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sequence', verbose_name='Tipe Dokumen'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('confirmed', 'Dikonfirmasi'), ('cancelled', 'Dibatalkan')], default='draft', max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Est. Harga'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.product', verbose_name='Produk'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='qty',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Jumlah'),
        ),
        migrations.AlterField(
            model_name='purchaserequestline',
            name='request_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.purchaserequest', verbose_name='Permintaan Pembelian'),
        ),
        migrations.CreateModel(
            name='QuickPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('reference', models.CharField(default=None, max_length=255, verbose_name='Referensi')),
                ('order_date', models.DateField(blank=True, default=None, null=True, verbose_name='Tanggal Pembelian')),
                ('payment_date', models.DateField(blank=True, default=None, null=True, verbose_name='Tanggal Bayar')),
                ('notes', models.TextField(blank=True, default=None, null=True, verbose_name='Catatan')),
                ('discount_type', models.CharField(blank=True, choices=[('per_product', 'Per Produk'), ('global', 'Diskon Global')], default='per_product', max_length=100, null=True, verbose_name='Tipe Diskon')),
                ('discount_method', models.CharField(blank=True, choices=[('percentage', 'Diskon (%)'), ('nominal', 'Diskon (Rp)')], default='percentage', max_length=100, null=True, verbose_name='Metode Diskon')),
                ('global_discount', models.FloatField(blank=True, default=0, null=True, verbose_name='Diskon Global')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Subtotal')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Diskon')),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Pajak')),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Total')),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='draft', max_length=100, null=True, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.paymentmethod', verbose_name='Metode Pembayaran')),
                ('sequence_id', models.ForeignKey(blank=True, help_text='Pilih format nomor dokumen Quick Purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sequence', verbose_name='Tipe Dokumen')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Quick Purchase',
                'verbose_name_plural': 'Quick Purchases',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='quick_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.quickpurchase', verbose_name='Quick Purchase'),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='quick_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.quickpurchase', verbose_name='Quick Purchase'),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='quick_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.quickpurchase', verbose_name='Quick Purchase'),
        ),
        migrations.CreateModel(
            name='QuickPurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.TextField(blank=True, default=None, null=True, verbose_name='Deskripsi')),
                ('qty', models.FloatField(blank=True, default=1, null=True, verbose_name='Jumlah')),
                ('uom', models.CharField(blank=True, default='pcs', max_length=255, null=True, verbose_name='UOM')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Harga Satuan')),
                ('discount_percentage', models.FloatField(blank=True, default=0, null=True, verbose_name='Diskon (%)')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Diskon')),
                ('tax_percentage', models.FloatField(blank=True, default=0, null=True, verbose_name='Pajak (%)')),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Pajak')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Total')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.product', verbose_name='Produk')),
                ('quick_purchase_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.quickpurchase', verbose_name='Quick Purchase')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Quick Purchase Line',
                'verbose_name_plural': 'Quick Purchase Lines',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
