# Generated by Django 6.0.6 on 2026-08-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_vendorpricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpricelist',
            name='end_date',
            field=models.DateField(blank=True, default=None, help_text='Kosongkan jika aktif terus (tanpa batas akhir)', null=True, verbose_name='Periode Selesai'),
        ),
        migrations.AddField(
            model_name='vendorpricelist',
            name='start_date',
            field=models.DateField(blank=True, default=None, help_text='Kosongkan jika berlaku sejak awal', null=True, verbose_name='Periode Mulai'),
        ),
    ]
