# Generated by Django 6.0.6 on 2026-08-25 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_vendorpricelist_end_date_vendorpricelist_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.salesorder', verbose_name='Sales Order'),
        ),
        migrations.CreateModel(
            name='QuickSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('reference', models.CharField(default=None, max_length=255, verbose_name='Referensi')),
                ('order_date', models.DateField(blank=True, default=None, null=True, verbose_name='Tanggal Penjualan')),
                ('payment_date', models.DateField(blank=True, default=None, null=True, verbose_name='Tanggal Bayar')),
                ('notes', models.TextField(blank=True, default=None, null=True, verbose_name='Catatan')),
                ('discount_type', models.CharField(blank=True, choices=[('per_product', 'Per Produk'), ('global', 'Diskon Global')], default='per_product', max_length=100, null=True, verbose_name='Tipe Diskon')),
                ('discount_method', models.CharField(blank=True, choices=[('percentage', 'Diskon (%)'), ('nominal', 'Diskon (Rp)')], default='percentage', max_length=100, null=True, verbose_name='Metode Diskon')),
                ('global_discount', models.FloatField(blank=True, default=0, null=True, verbose_name='Diskon Global')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Subtotal')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Diskon')),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Pajak')),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Total')),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='draft', max_length=100, null=True, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customer', verbose_name='Customer')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.paymentmethod', verbose_name='Metode Pembayaran')),
                ('sequence_id', models.ForeignKey(blank=True, help_text='Pilih format nomor dokumen Quick Sales', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sequence', verbose_name='Tipe Dokumen')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Quick Sales',
                'verbose_name_plural': 'Quick Sales',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='quick_sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.quicksales', verbose_name='Quick Sales'),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='quick_sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.quicksales', verbose_name='Quick Sales'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='quick_sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.quicksales', verbose_name='Quick Sales'),
        ),
        migrations.CreateModel(
            name='QuickSalesLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.TextField(blank=True, default=None, null=True, verbose_name='Deskripsi')),
                ('qty', models.FloatField(blank=True, default=1, null=True, verbose_name='Jumlah')),
                ('uom', models.CharField(blank=True, default='pcs', max_length=255, null=True, verbose_name='UOM')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Harga Satuan')),
                ('discount_percentage', models.FloatField(blank=True, default=0, null=True, verbose_name='Diskon (%)')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Diskon')),
                ('tax_percentage', models.FloatField(blank=True, default=0, null=True, verbose_name='Pajak (%)')),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Pajak')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Total')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.product', verbose_name='Produk')),
                ('quick_sales_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.quicksales', verbose_name='Quick Sales')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Quick Sales Line',
                'verbose_name_plural': 'Quick Sales Lines',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
