# Generated by Django 6.0.6 on 2026-08-25 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_alter_deliveryorder_sales_order_quicksales_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPricelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(default=None, help_text='Contoh: Retail Pricelist, Grosir Pricelist', max_length=255, verbose_name='Nama Pricelist')),
                ('start_date', models.DateField(blank=True, default=None, help_text='Kosongkan jika berlaku sejak awal', null=True, verbose_name='Periode Mulai')),
                ('end_date', models.DateField(blank=True, default=None, help_text='Kosongkan jika aktif terus (tanpa batas akhir)', null=True, verbose_name='Periode Selesai')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Sales Pricelist',
                'verbose_name_plural': 'Sales Pricelists',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesPricelistLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('uom', models.CharField(blank=True, default='pcs', max_length=255, null=True, verbose_name='UOM')),
                ('min_qty', models.FloatField(blank=True, default=1, null=True, verbose_name='Min Qty')),
                ('max_qty', models.FloatField(blank=True, default=None, help_text='Kosongkan jika tanpa batas atas', null=True, verbose_name='Max Qty')),
                ('fix_price', models.DecimalField(decimal_places=2, default=None, max_digits=18, verbose_name='Fix Price')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('pricelist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.salespricelist', verbose_name='Pricelist')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.product', verbose_name='Produk')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Sales Pricelist Line',
                'verbose_name_plural': 'Sales Pricelist Lines',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
