# Generated by Django 6.0.6 on 2026-08-25 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_salespricelist_salespricelistline'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicksales',
            name='pricelist',
            field=models.ForeignKey(blank=True, help_text='Pilih pricelist untuk autofill harga jual sesuai rentang qty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.salespricelist', verbose_name='Pricelist'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='pricelist',
            field=models.ForeignKey(blank=True, help_text='Pilih pricelist untuk autofill harga jual sesuai rentang qty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.salespricelist', verbose_name='Pricelist'),
        ),
    ]
