# Generated by Django 6.0.6 on 2026-08-25 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_quicksales_pricelist_salesorder_pricelist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryorder',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Pengiriman Barang', 'verbose_name_plural': 'Pengiriman Barang'},
        ),
        migrations.AlterModelOptions(
            name='deliveryorderline',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Baris Pengiriman Barang', 'verbose_name_plural': 'Baris Pengiriman Barang'},
        ),
        migrations.AlterModelOptions(
            name='goodsreceipt',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Penerimaan Barang', 'verbose_name_plural': 'Penerimaan Barang'},
        ),
        migrations.AlterModelOptions(
            name='goodsreceiptline',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Baris Penerimaan Barang', 'verbose_name_plural': 'Baris Penerimaan Barang'},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Penjualan', 'verbose_name_plural': 'Penjualan'},
        ),
        migrations.AlterModelOptions(
            name='salesorderline',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Baris Sales Order', 'verbose_name_plural': 'Baris Sales Order'},
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.salesorder', verbose_name='SO'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='address',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Alamat Pengiriman'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='delivery_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Tanggal Kirim'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='reference',
            field=models.CharField(default=None, max_length=255, verbose_name='Referensi'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.salesorder', verbose_name='SO'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='sequence_id',
            field=models.ForeignKey(blank=True, help_text='Pilih format nomor dokumen pengiriman barang', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sequence', verbose_name='Tipe Dokumen'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('waiting', 'Menunggu'), ('done', 'Selesai'), ('cancelled', 'Dibatalkan')], default='draft', max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='warehouse',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Gudang'),
        ),
        migrations.AlterField(
            model_name='deliveryorderline',
            name='delivered_qty',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Qty Terkirim'),
        ),
        migrations.AlterField(
            model_name='deliveryorderline',
            name='delivery_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.deliveryorder', verbose_name='Pengiriman Barang'),
        ),
        migrations.AlterField(
            model_name='deliveryorderline',
            name='name',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='deliveryorderline',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Harga Satuan'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.purchaseorder', verbose_name='PO'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='receipt_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Tanggal Terima'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='reference',
            field=models.CharField(default=None, max_length=255, verbose_name='Referensi'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='sequence_id',
            field=models.ForeignKey(blank=True, help_text='Pilih format nomor dokumen penerimaan barang', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sequence', verbose_name='Tipe Dokumen'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('waiting', 'Menunggu'), ('done', 'Selesai'), ('cancelled', 'Dibatalkan')], default='draft', max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='warehouse',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Gudang'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='name',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='receipt_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.goodsreceipt', verbose_name='Penerimaan Barang'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='received_qty',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Qty Diterima'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Harga Satuan'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Diskon'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='discount_method',
            field=models.CharField(blank=True, choices=[('percentage', 'Diskon (%)'), ('nominal', 'Diskon (Rp)')], default='percentage', max_length=100, null=True, verbose_name='Metode Diskon'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('per_product', 'Per Produk'), ('global', 'Diskon Global')], default='per_product', max_length=100, null=True, verbose_name='Tipe Diskon'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='expected_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Perkiraan Tanggal Terima'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='global_discount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Diskon Global'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='manual_discount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Diskon Manual (%)'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Tanggal Pesanan'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='reference',
            field=models.CharField(default=None, max_length=255, verbose_name='Referensi'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='sequence_id',
            field=models.ForeignKey(blank=True, help_text='Pilih format nomor dokumen (SO Local / SO Online, dll)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sequence', verbose_name='Tipe Dokumen'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('confirmed', 'Dikonfirmasi'), ('done', 'Selesai'), ('cancelled', 'Dibatalkan')], default='draft', max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Pajak'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Diskon'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='discount_percentage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Diskon (%)'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='name',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.salesorder', verbose_name='SO'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Harga Satuan'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='qty',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Jumlah'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Pajak'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='tax_percentage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Pajak (%)'),
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Nama Lokasi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('warehouse_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouse', verbose_name='Gudang')),
            ],
            options={
                'verbose_name': 'Lokasi Gudang',
                'verbose_name_plural': 'Lokasi Gudang',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
