# Generated by Django 6.0.6 on 2026-08-25 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_alter_deliveryorder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('reference', models.CharField(default=None, max_length=255, verbose_name='Referensi')),
                ('transfer_date', models.DateField(blank=True, default=None, null=True, verbose_name='Tanggal Transfer')),
                ('notes', models.TextField(blank=True, default=None, null=True, verbose_name='Keterangan')),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('confirmed', 'Dikonfirmasi'), ('cancelled', 'Dibatalkan')], default='draft', max_length=100, null=True, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('destination_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouselocation', verbose_name='Lokasi Tujuan')),
                ('destination_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouse', verbose_name='Gudang Tujuan')),
                ('source_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouselocation', verbose_name='Lokasi Asal')),
                ('source_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouse', verbose_name='Gudang Asal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Terima Stock',
                'verbose_name_plural': 'Terima Stock',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockInLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.TextField(blank=True, default=None, null=True, verbose_name='Deskripsi')),
                ('uom', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='UOM')),
                ('received_qty', models.FloatField(blank=True, default=0, null=True, verbose_name='Qty Diterima')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('in_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.stockin', verbose_name='Terima Stock')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.product', verbose_name='Product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Baris Terima Stock',
                'verbose_name_plural': 'Baris Terima Stock',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('reference', models.CharField(default=None, max_length=255, verbose_name='Referensi')),
                ('transfer_date', models.DateField(blank=True, default=None, null=True, verbose_name='Tanggal Transfer')),
                ('notes', models.TextField(blank=True, default=None, null=True, verbose_name='Keterangan')),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('confirmed', 'Dikonfirmasi'), ('cancelled', 'Dibatalkan')], default='draft', max_length=100, null=True, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('destination_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouselocation', verbose_name='Lokasi Tujuan')),
                ('destination_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouse', verbose_name='Gudang Tujuan')),
                ('source_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouselocation', verbose_name='Lokasi Asal')),
                ('source_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouse', verbose_name='Gudang Asal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Stock Keluar',
                'verbose_name_plural': 'Stock Keluar',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stockin',
            name='transfer_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.stockout', verbose_name='Transfer Keluar'),
        ),
        migrations.CreateModel(
            name='StockOutLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.TextField(blank=True, default=None, null=True, verbose_name='Deskripsi')),
                ('uom', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='UOM')),
                ('transfer_qty', models.FloatField(blank=True, default=0, null=True, verbose_name='Transfer Qty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('out_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.stockout', verbose_name='Stock Keluar')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.product', verbose_name='Product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Baris Stock Keluar',
                'verbose_name_plural': 'Baris Stock Keluar',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('reference', models.CharField(default=None, max_length=255, verbose_name='Referensi')),
                ('deadline', models.DateField(blank=True, default=None, null=True, verbose_name='Deadline Request')),
                ('notes', models.TextField(blank=True, default=None, null=True, verbose_name='Keterangan')),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('confirmed', 'Dikonfirmasi'), ('cancelled', 'Dibatalkan')], default='draft', max_length=100, null=True, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('destination_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouselocation', verbose_name='Lokasi Tujuan')),
                ('destination_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouse', verbose_name='Gudang Tujuan')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.user', verbose_name='User Request')),
                ('source_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouselocation', verbose_name='Lokasi Asal')),
                ('source_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouse', verbose_name='Gudang Asal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Request Transfer',
                'verbose_name_plural': 'Request Transfer',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stockout',
            name='request_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.stockrequest', verbose_name='Nomor Transfer Request'),
        ),
        migrations.CreateModel(
            name='StockRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.TextField(blank=True, default=None, null=True, verbose_name='Deskripsi')),
                ('uom', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='UOM')),
                ('request_qty', models.FloatField(blank=True, default=0, null=True, verbose_name='Request Qty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.product', verbose_name='Product')),
                ('request_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.stockrequest', verbose_name='Request Transfer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Baris Request Transfer',
                'verbose_name_plural': 'Baris Request Transfer',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
