# Generated by Django 6.0.6 on 2026-08-27 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_stockin_stockinline_stockout_stockin_transfer_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Mapping unit ke product inventory — dipakai saat input penjualan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.product', verbose_name='Product'),
        ),
    ]
