# Generated by Django 6.0.6 on 2026-08-29 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_unit_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='product',
        ),
    ]
