# Generated by Django 6.0.6 on 2026-08-29 04:06

import django.db.models.deletion
from django.db import migrations, models


def backfill_customer_from_name(apps, schema_editor):
    """Backfill project_unit_detail.customer dari kolom name (string nama customer).

    - name = nama customer yang diinput wizard lama → lookup Customer by name,
      get_or_create kalau belum ada (mis. 'Krisma' yang tidak ada di master).
    """
    ProjectUnitDetail = apps.get_model('core', 'ProjectUnitDetail')
    Customer = apps.get_model('core', 'Customer')
    for d in ProjectUnitDetail.objects.exclude(name='').exclude(name__isnull=True):
        name = (d.name or '').strip()
        if not name:
            continue
        cust, _ = Customer.objects.get_or_create(name=name)
        d.customer_id = cust.pk
        d.save(update_fields=['customer_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_remove_unit_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='unit_detail',
            field=models.ForeignKey(blank=True, help_text='Detail Unit proyek yang dijual lewat invoice ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.projectunitdetail', verbose_name='Detail Unit'),
        ),
        migrations.AddField(
            model_name='projectunitdetail',
            name='customer',
            field=models.ForeignKey(help_text='Customer pembeli unit ini (dari master Customer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customer', verbose_name='Nama Customer'),
        ),
        migrations.RunPython(backfill_customer_from_name, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='projectunitdetail',
            name='name',
        ),
    ]
