# Generated by Django 6.0.6 on 2026-08-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_remove_projectunitdetail_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdetailpayment',
            name='payment_method',
            field=models.CharField(blank=True, default=None, help_text='Metode pembayaran penerimaan', max_length=255, null=True, verbose_name='Metode'),
        ),
        migrations.AlterField(
            model_name='unitdetailpayment',
            name='name',
            field=models.CharField(default=None, help_text='Nomor dokumen penerimaan (receipt)', max_length=255, verbose_name='Pembayaran'),
        ),
    ]
