# Generated by Django 6.0.6 on 2026-08-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_unitdetailpayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdetailpayment',
            name='payment_ref',
            field=models.CharField(blank=True, default=None, help_text='No. Cek / Transfer / dll dari penerimaan', max_length=255, null=True, verbose_name='Ref. Pembayaran'),
        ),
        migrations.AlterField(
            model_name='unitdetailpayment',
            name='name',
            field=models.CharField(default=None, help_text='Nomor dokumen penerimaan (receipt)', max_length=255, verbose_name='No Faktur'),
        ),
    ]
