# Generated by Django 6.0.6 on 2026-08-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_unitdetailpayment_payment_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdetailprogress',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Budget'),
        ),
        migrations.AddField(
            model_name='unitdetailprogress',
            name='catatan',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Catatan'),
        ),
        migrations.AddField(
            model_name='unitdetailprogress',
            name='date_done',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Tanggal Selesai'),
        ),
        migrations.AddField(
            model_name='unitdetailprogress',
            name='mandor',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Mandor/Pemborong'),
        ),
        migrations.AddField(
            model_name='unitdetailprogress',
            name='realisasi_budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Realisasi Budget'),
        ),
        migrations.AddField(
            model_name='unitdetailprogress',
            name='selisih',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Selisih'),
        ),
        migrations.AddField(
            model_name='unitdetailprogress',
            name='selisih_budget',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Selisih Budget'),
        ),
        migrations.AlterField(
            model_name='unitdetailprogress',
            name='date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Target Selesai'),
        ),
        migrations.AlterField(
            model_name='unitdetailprogress',
            name='progress',
            field=models.CharField(blank=True, choices=[('perencanaan', 'Perencanaan'), ('dalam_proses', 'Dalam Proses'), ('selesai', 'Selesai')], default='perencanaan', max_length=100, null=True, verbose_name='Progress'),
        ),
    ]
