# Generated by Django 6.0.6 on 2026-08-29 13:52

import django.db.models.deletion
from django.db import migrations, models


# Mapping nilai satuan lama (char) -> pk Uom hasil backfill
_UOM_MAP = {}


def copy_uom_values(apps, schema_editor):
    """Salin nilai satuan lama (char) ke kolom temp sebelum kolom di-drop."""
    Product = apps.get_model('core', 'Product')
    for p in Product.objects.all():
        if p.uom:
            Product.objects.filter(pk=p.pk).update(uom_char_temp=p.uom)


def backfill_uoms(apps, schema_editor):
    """Buat master Uom untuk nilai satuan produk yang belum ada di master."""
    Product = apps.get_model('core', 'Product')
    Uom = apps.get_model('core', 'Uom')
    values = (
        Product.objects.exclude(uom__isnull=True).exclude(uom='')
        .values_list('uom', flat=True).distinct()
    )
    for v in values:
        existing = (
            Uom.objects.filter(code__iexact=v).first()
            or Uom.objects.filter(name__iexact=v).first()
        )
        if existing is None:
            existing = Uom.objects.create(code=v, name=v, is_active=True)
        _UOM_MAP[v] = existing.pk


def link_product_uoms(apps, schema_editor):
    """Hubungkan produk ke Uom master (kolom uom_id) dari nilai char lama."""
    Product = apps.get_model('core', 'Product')
    for p in Product.objects.exclude(uom_char_temp__isnull=True).exclude(uom_char_temp=''):
        pk = _UOM_MAP.get(p.uom_char_temp)
        if pk:
            Product.objects.filter(pk=p.pk).update(uom_id=pk)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_unitdetailprogress_budget_unitdetailprogress_catatan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinvoice',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Faktur', 'verbose_name_plural': 'Faktur'},
        ),
        migrations.AlterModelOptions(
            name='customerinvoiceline',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Baris Faktur', 'verbose_name_plural': 'Baris Faktur'},
        ),
        migrations.AlterModelOptions(
            name='customerreceipt',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Penerimaan', 'verbose_name_plural': 'Penerimaan'},
        ),
        migrations.AlterModelOptions(
            name='customerreceiptline',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Baris Penerimaan', 'verbose_name_plural': 'Baris Penerimaan'},
        ),
        migrations.AlterModelOptions(
            name='expenseline',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Baris Biaya', 'verbose_name_plural': 'Baris Biaya'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Produk', 'verbose_name_plural': 'Produk'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategori'},
        ),
        migrations.AlterModelOptions(
            name='vendorbill',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Tagihan', 'verbose_name_plural': 'Tagihan'},
        ),
        migrations.AlterModelOptions(
            name='vendorbillline',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Baris Tagihan', 'verbose_name_plural': 'Baris Tagihan'},
        ),
        migrations.AlterModelOptions(
            name='vendorpayment',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Pembayaran', 'verbose_name_plural': 'Pembayaran'},
        ),
        migrations.AlterModelOptions(
            name='vendorpaymentline',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Baris Pembayaran', 'verbose_name_plural': 'Baris Pembayaran'},
        ),
        migrations.AddField(
            model_name='product',
            name='tipe_product',
            field=models.CharField(blank=True, choices=[('Stock', 'Stock'), ('Non Stock', 'Non Stock')], default='Stock', max_length=100, null=True, verbose_name='Tipe Produk'),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Diskon'),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='down_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Jumlah DP'),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Sisa Tagihan'),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Jatuh Tempo'),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='invoice_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Tanggal Faktur'),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='is_down_payment',
            field=models.BooleanField(default=False, verbose_name='Faktur DP'),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='manual_discount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Diskon Manual (%)'),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Sudah Dibayar'),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('unpaid', 'Belum Dibayar'), ('partial', 'Sebagian'), ('paid', 'Lunas')], default='unpaid', max_length=100, null=True, verbose_name='Status Pembayaran'),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='reference',
            field=models.CharField(default=None, max_length=255, verbose_name='Referensi'),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.salesorder', verbose_name='Penjualan'),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Pajak'),
        ),
        migrations.AlterField(
            model_name='customerinvoiceline',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Diskon'),
        ),
        migrations.AlterField(
            model_name='customerinvoiceline',
            name='discount_percentage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Diskon (%)'),
        ),
        migrations.AlterField(
            model_name='customerinvoiceline',
            name='invoice_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customerinvoice', verbose_name='Faktur'),
        ),
        migrations.AlterField(
            model_name='customerinvoiceline',
            name='name',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='customerinvoiceline',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Harga Satuan'),
        ),
        migrations.AlterField(
            model_name='customerinvoiceline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.product', verbose_name='Produk'),
        ),
        migrations.AlterField(
            model_name='customerinvoiceline',
            name='qty',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Jumlah'),
        ),
        migrations.AlterField(
            model_name='customerinvoiceline',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Pajak'),
        ),
        migrations.AlterField(
            model_name='customerinvoiceline',
            name='tax_percentage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Pajak (%)'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='payment_date',
            field=models.DateField(default=None, verbose_name='Tanggal Penerimaan'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.paymentmethod', verbose_name='Metode Pembayaran'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='payment_ref',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Referensi Pembayaran'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='reference',
            field=models.CharField(default=None, max_length=255, verbose_name='Referensi'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Sisa Alokasi'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='total_allocation',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Total Alokasi'),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Total Penerimaan'),
        ),
        migrations.AlterField(
            model_name='customerreceiptline',
            name='invoice_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customerinvoice', verbose_name='Faktur'),
        ),
        migrations.AlterField(
            model_name='customerreceiptline',
            name='receipt_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customerreceipt', verbose_name='Penerimaan'),
        ),
        migrations.AlterField(
            model_name='customerreceiptline',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=18, verbose_name='Jumlah Diterima'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='milestone_line',
            field=models.ForeignKey(blank=True, help_text='Sub-line milestone terkait (dari wizard Input Expenses)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.milestoneline', verbose_name='Baris Milestone'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.paymentmethod', verbose_name='Metode Pembayaran'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='reference',
            field=models.CharField(default=None, max_length=255, verbose_name='Referensi'),
        ),
        migrations.AlterField(
            model_name='expenseline',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Wajib diisi saat POST', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.chartofaccount', verbose_name='Akun'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.productcategory', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='SKU / Kode'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Harga Beli'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='Nama Produk'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Harga Jual'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom_char_temp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(copy_uom_values, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(backfill_uoms, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='product',
            name='uom',
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.uom', verbose_name='Satuan'),
        ),
        migrations.RunPython(link_product_uoms, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='product',
            name='uom_char_temp',
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Berat (kg)'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Kode Kategori'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='Nama Kategori'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='bill_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Tanggal Tagihan'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Diskon'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='down_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Jumlah DP'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Sisa Tagihan'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Jatuh Tempo'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='is_down_payment',
            field=models.BooleanField(default=False, verbose_name='Tagihan DP'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='manual_discount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Diskon Manual (%)'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='milestone_line',
            field=models.ForeignKey(blank=True, help_text='Sub-line milestone terkait (dari wizard Buat Tagihan)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.milestoneline', verbose_name='Baris Milestone'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Sudah Dibayar'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('unpaid', 'Belum Dibayar'), ('partial', 'Sebagian'), ('paid', 'Lunas')], default='unpaid', max_length=100, null=True, verbose_name='Status Pembayaran'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='reference',
            field=models.CharField(default=None, max_length=255, verbose_name='Referensi'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Pajak'),
        ),
        migrations.AlterField(
            model_name='vendorbillline',
            name='bill_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.vendorbill', verbose_name='Tagihan'),
        ),
        migrations.AlterField(
            model_name='vendorbillline',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Diskon'),
        ),
        migrations.AlterField(
            model_name='vendorbillline',
            name='discount_percentage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Diskon (%)'),
        ),
        migrations.AlterField(
            model_name='vendorbillline',
            name='name',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='vendorbillline',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Harga Satuan'),
        ),
        migrations.AlterField(
            model_name='vendorbillline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.product', verbose_name='Produk'),
        ),
        migrations.AlterField(
            model_name='vendorbillline',
            name='qty',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Jumlah'),
        ),
        migrations.AlterField(
            model_name='vendorbillline',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Pajak'),
        ),
        migrations.AlterField(
            model_name='vendorbillline',
            name='tax_percentage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Pajak (%)'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='payment_date',
            field=models.DateField(default=None, verbose_name='Tanggal Pembayaran'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.paymentmethod', verbose_name='Metode Pembayaran'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='payment_ref',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Referensi Pembayaran'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='reference',
            field=models.CharField(default=None, max_length=255, verbose_name='Referensi'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Sisa Alokasi'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='total_allocation',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Total Alokasi'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Total Pembayaran'),
        ),
        migrations.AlterField(
            model_name='vendorpaymentline',
            name='bill_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.vendorbill', verbose_name='Tagihan'),
        ),
        migrations.AlterField(
            model_name='vendorpaymentline',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=18, verbose_name='Alokasi Pembayaran'),
        ),
        migrations.AlterField(
            model_name='vendorpaymentline',
            name='payment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.vendorpayment', verbose_name='Pembayaran'),
        ),
    ]
