# Generated by Django 6.0.6 on 2026-08-29 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_alter_customerinvoice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Metode Pembayaran', 'verbose_name_plural': 'Metode Pembayaran'},
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='account',
            field=models.ForeignKey(help_text='Akun default untuk metode pembayaran ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.chartofaccount', verbose_name='Akun Perkiraan'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
    ]
