# Generated by Django 6.0.6 on 2026-08-29 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_alter_paymentmethod_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deposit_type', models.CharField(choices=[('terima', 'Terima Deposit'), ('bayar', 'Bayar Deposit')], default='terima', max_length=100, verbose_name='Tipe Deposit')),
                ('deposit_date', models.DateField(default=None, verbose_name='Tanggal')),
                ('amount', models.DecimalField(decimal_places=2, default=None, max_digits=18, verbose_name='Nominal')),
                ('notes', models.TextField(blank=True, default=None, null=True, verbose_name='Catatan')),
                ('bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.paymentmethod', verbose_name='Kas/Bank')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(blank=True, help_text='Customer pemberi deposit (Tipe Deposit: Terima)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customer', verbose_name='Customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('vendor', models.ForeignKey(blank=True, help_text='Vendor penerima deposit (Tipe Deposit: Bayar)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposit',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransferCashBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('transfer_date', models.DateField(default=None, verbose_name='Tanggal')),
                ('amount', models.DecimalField(decimal_places=2, default=None, max_digits=18, verbose_name='Nominal')),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Biaya Admin')),
                ('notes', models.TextField(blank=True, default=None, null=True, verbose_name='Catatan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('fee_account', models.ForeignKey(blank=True, help_text='Akun beban untuk biaya admin transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.chartofaccount', verbose_name='Akun Biaya Admin')),
                ('from_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.paymentmethod', verbose_name='Kas/Bank Asal')),
                ('to_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.paymentmethod', verbose_name='Kas/Bank Tujuan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Transfer Kas/Bank',
                'verbose_name_plural': 'Transfer Kas/Bank',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
