# Generated by Django 6.0.6 on 2026-08-29 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_deposit_transfercashbank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouselocation', verbose_name='Lokasi Pengambilan'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouselocation', verbose_name='Lokasi Penyimpanan'),
        ),
        # warehouse berubah CharField → FK: Remove+Add agar cast varchar→int tidak gagal
        # (nilai lama hanya free text, tidak dipertahankan)
        migrations.RemoveField(
            model_name='deliveryorder',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouse', verbose_name='Gudang'),
        ),
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouse', verbose_name='Gudang'),
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date', models.DateField(blank=True, default=None, null=True, verbose_name='Tanggal')),
                ('quantity', models.FloatField(blank=True, default=0, null=True, verbose_name='Qty (+/-)')),
                ('source_model', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Model Sumber')),
                ('source_reference', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Referensi Sumber')),
                ('source_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='ID Sumber')),
                ('source_line_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='ID Baris Sumber')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Harga Satuan')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Deskripsi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouselocation', verbose_name='Lokasi')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.product', verbose_name='Product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Stock Ledger',
                'verbose_name_plural': 'Stock Ledger',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
