# Generated by Django 6.0.6 on 2026-08-29 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_deliveryorder_location_goodsreceipt_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouselocation', verbose_name='Lokasi Pengambilan'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouse', verbose_name='Gudang'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouselocation', verbose_name='Lokasi Penyimpanan'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouse', verbose_name='Gudang'),
        ),
    ]
