# Generated by Django 6.0.6 on 2026-08-29 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_alter_deliveryorder_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouselocation', verbose_name='Lokasi Tujuan'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouse', verbose_name='Gudang Tujuan'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouselocation', verbose_name='Lokasi Asal'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouse', verbose_name='Gudang Asal'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouselocation', verbose_name='Lokasi Tujuan'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouse', verbose_name='Gudang Tujuan'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouselocation', verbose_name='Lokasi Asal'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouse', verbose_name='Gudang Asal'),
        ),
    ]
