# Generated by Django 6.0.6 on 2026-08-30 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_alter_stockin_destination_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequest',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouselocation', verbose_name='Lokasi Tujuan'),
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouse', verbose_name='Gudang Tujuan'),
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouselocation', verbose_name='Lokasi Asal'),
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouse', verbose_name='Gudang Asal'),
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('confirmed', 'Dalam Proses'), ('cancelled', 'Dibatalkan')], default='draft', max_length=100, null=True, verbose_name='Status'),
        ),
    ]
