# Generated by Django 6.0.6 on 2026-08-30 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_alter_stockrequest_destination_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='sequence_id',
            field=models.ForeignKey(blank=True, help_text='Pilih format nomor dokumen (SR, dll)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sequence', verbose_name='Tipe Dokumen'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='sequence_id',
            field=models.ForeignKey(blank=True, help_text='Pilih format nomor dokumen (SOUT, dll)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sequence', verbose_name='Tipe Dokumen'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='sequence_id',
            field=models.ForeignKey(blank=True, help_text='Pilih format nomor dokumen (SIN, dll)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sequence', verbose_name='Tipe Dokumen'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='request_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.stockrequest', verbose_name='Nomor Request'),
        ),
    ]
