# Generated by Django 6.0.6 on 2026-08-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_stockrequest_sequence_id_stockout_sequence_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockin',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('waiting', 'Menunggu'), ('done', 'Selesai'), ('cancelled', 'Dibatalkan')], default='draft', max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('waiting', 'Menunggu'), ('done', 'Selesai'), ('cancelled', 'Dibatalkan')], default='draft', max_length=100, null=True, verbose_name='Status'),
        ),
    ]
