# Generated by Django 6.0.6 on 2026-08-30 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_alter_stockin_status_alter_stockout_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('reference', models.CharField(default=None, max_length=255, verbose_name='Referensi')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Nama Stock Count')),
                ('adjustment_date', models.DateField(default=None, verbose_name='Tanggal')),
                ('notes', models.TextField(blank=True, default=None, null=True, verbose_name='Catatan')),
                ('total_selisih', models.FloatField(blank=True, default=0, null=True, verbose_name='Total Selisih')),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('done', 'Selesai'), ('cancelled', 'Dibatalkan')], default='draft', max_length=100, null=True, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouselocation', verbose_name='Lokasi')),
                ('sequence_id', models.ForeignKey(blank=True, help_text='Pilih format nomor dokumen (ADJ, dll)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.sequence', verbose_name='Tipe Dokumen')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.warehouse', verbose_name='Gudang')),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'verbose_name_plural': 'Stock Adjustment',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.TextField(blank=True, default=None, null=True, verbose_name='Deskripsi')),
                ('uom', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='UOM')),
                ('stock_sistem', models.FloatField(blank=True, default=0, null=True, verbose_name='Stock Sistem')),
                ('selisih', models.FloatField(blank=True, default=0, help_text='Selisih fisik vs sistem (boleh minus)', null=True, verbose_name='Selisih')),
                ('stock_akhir', models.FloatField(blank=True, default=0, null=True, verbose_name='Stock Akhir')),
                ('adjustment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.stockadjustment', verbose_name='Stock Adjustment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.product', verbose_name='Product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Baris Stock Adjustment',
                'verbose_name_plural': 'Baris Stock Adjustment',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
