# Generated by Django 6.0.6 on 2026-08-31 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_alter_stockadjustment_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(default=None, help_text='Misal: Excavator, Komputer, Kendaraan Operasional', max_length=255, verbose_name='Nama Aset')),
                ('code', models.CharField(blank=True, default=None, help_text='Kode internal aset, misal: AST-001', max_length=255, null=True, verbose_name='Kode Aset')),
                ('location', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Lokasi Aset')),
                ('acquisition_date', models.DateField(blank=True, default=None, null=True, verbose_name='Tanggal Perolehan')),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Nilai Perolehan')),
                ('useful_life_months', models.IntegerField(blank=True, default=None, help_text='Jumlah bulan penyusutan linear', null=True, verbose_name='Masa Penyusutan (Bulan)')),
                ('first_depreciation_date', models.DateField(blank=True, default=None, help_text='Bulan pertama depresiasi dimulai', null=True, verbose_name='Tanggal Pertama Depresiasi')),
                ('accumulated_depreciation_account', models.ForeignKey(blank=True, help_text='Akun COA untuk akumulasi penyusutan (neraca)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.chartofaccount', verbose_name='Akun Akumulasi Penyusutan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('depreciation_expense_account', models.ForeignKey(blank=True, help_text='Akun COA untuk beban penyusutan (laba rugi)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.chartofaccount', verbose_name='Akun Beban Penyusutan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Aset',
                'verbose_name_plural': 'Aset',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date', models.DateField(blank=True, default=None, null=True, verbose_name='Tanggal')),
                ('asset_value', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Nilai Aset')),
                ('depreciation', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Depresiasi')),
                ('residual_value', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Sisa Nilai')),
                ('asset_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.asset', verbose_name='Aset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Baris Depresiasi',
                'verbose_name_plural': 'Baris Depresiasi',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
