# Generated by Django 6.0.6 on 2026-09-01 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_asset_assetdepreciationline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInvoiceInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('term_no', models.IntegerField(blank=True, default=None, null=True, verbose_name='Cicilan Ke')),
                ('due_date', models.DateField(blank=True, default=None, null=True, verbose_name='Jatuh Tempo')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, verbose_name='Nominal')),
                ('note', models.TextField(blank=True, default=None, null=True, verbose_name='Catatan')),
                ('payment_status', models.CharField(blank=True, choices=[('unpaid', 'Belum Dibayar'), ('partial', 'Sebagian'), ('paid', 'Lunas')], default='unpaid', max_length=100, null=True, verbose_name='Status Pembayaran')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('invoice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customerinvoice', verbose_name='Faktur')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Cicilan',
                'verbose_name_plural': 'Cicilan',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
