# Generated by Django 6.0.6 on 2026-09-02 13:28
# Manual reorder: CreateModel Tax → AddField m2m → backfill legacy tax_percentage
# → RemoveField tax_percentage (urutan penting agar data lama tidak hilang).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

LINE_MODELS = (
    ('CustomerInvoiceLine', 'customerinvoiceline'),
    ('VendorBillLine', 'vendorbillline'),
    ('SalesOrderLine', 'salesorderline'),
    ('PurchaseOrderLine', 'purchaseorderline'),
    ('QuickSalesLine', 'quicksalesline'),
    ('QuickPurchaseLine', 'quickpurchaseline'),
)


def backfill_taxes(apps, schema_editor):
    """Backfill: baris legacy dgn tax_percentage > 0 → Tax (rate sama) + link m2m.

    Tax lama dibikin dengan nama generik 'Pajak {rate}%' bila belum ada Tax
    dengan rate tersebut; tax master resmi (PPN/PPh) tetap dibuat terpisah.
    """
    Tax = apps.get_model('core', 'Tax')
    for model_name, _table in LINE_MODELS:
        LineModel = apps.get_model('core', model_name)
        qs = LineModel.objects.filter(tax_percentage__gt=0).only('id', 'tax_percentage')
        for line in qs:
            rate = float(line.tax_percentage or 0)
            if rate <= 0:
                continue
            tax, _ = Tax.objects.get_or_create(
                rate=rate,
                defaults={'name': f'Pajak {rate:g}%'},
            )
            line.taxes.add(tax)


def seed_default_taxes(apps, schema_editor):
    """Seed master tax default: PPN 11% & PPh 23 2% (skip bila sudah ada)."""
    Tax = apps.get_model('core', 'Tax')
    defaults = [
        ('PPN', 11.0),
        ('PPh 23', 2.0),
    ]
    for name, rate in defaults:
        Tax.objects.get_or_create(
            rate=rate,
            defaults={'name': name, 'is_active': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_customerinvoiceinstallment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(default=None, help_text='Contoh: PPN, PPh 23', max_length=255, verbose_name='Nama Pajak')),
                ('rate', models.FloatField(default=0, help_text='Persentase tarif pajak, mis. 11 untuk PPN 11%', verbose_name='Tarif (%)')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Pajak',
                'verbose_name_plural': 'Pajak',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customerinvoiceline',
            name='taxes',
            field=models.ManyToManyField(blank=True, help_text='Pilih satu atau lebih pajak (PPN, PPh, dll)', related_name='+', to='core.tax', verbose_name='Pajak'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='taxes',
            field=models.ManyToManyField(blank=True, help_text='Pilih satu atau lebih pajak (PPN, PPh, dll)', related_name='+', to='core.tax', verbose_name='Pajak'),
        ),
        migrations.AddField(
            model_name='quickpurchaseline',
            name='taxes',
            field=models.ManyToManyField(blank=True, help_text='Pilih satu atau lebih pajak (PPN, PPh, dll)', related_name='+', to='core.tax', verbose_name='Pajak'),
        ),
        migrations.AddField(
            model_name='quicksalesline',
            name='taxes',
            field=models.ManyToManyField(blank=True, help_text='Pilih satu atau lebih pajak (PPN, PPh, dll)', related_name='+', to='core.tax', verbose_name='Pajak'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='taxes',
            field=models.ManyToManyField(blank=True, help_text='Pilih satu atau lebih pajak (PPN, PPh, dll)', related_name='+', to='core.tax', verbose_name='Pajak'),
        ),
        migrations.AddField(
            model_name='vendorbillline',
            name='taxes',
            field=models.ManyToManyField(blank=True, help_text='Pilih satu atau lebih pajak (PPN, PPh, dll)', related_name='+', to='core.tax', verbose_name='Pajak'),
        ),
        migrations.RunPython(seed_default_taxes),
        migrations.RunPython(backfill_taxes),
        migrations.RemoveField(
            model_name='customerinvoiceline',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='quickpurchaseline',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='quicksalesline',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='salesorderline',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='vendorbillline',
            name='tax_percentage',
        ),
    ]
