# Generated by Django 6.0.6 on 2026-09-05 03:09 — disaring manual.
# Catatan: AlterField tax_amount (6 line model) TIDAK disertakan — drift
# pra-existing dari refactor pajak (d267f1b), di luar scope task unit.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_customerreceiptline_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='luas_bangunan',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Luas Bangunan (m²)'),
        ),
        migrations.AddField(
            model_name='unit',
            name='luas_tanah',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Luas Tanah (m²)'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(default=None, help_text='Otomatis dari Luas Bangunan / Luas Tanah (mis. 40/62)', max_length=255, verbose_name='Unit Produk'),
        ),
    ]
