# Generated by Django 6.0.6 on 2026-09-05 03:21 — disaring manual.
# Catatan: AlterField tax_amount (6 line model) TIDAK disertakan — drift
# pra-existing dari refactor pajak (d267f1b), di luar scope task unit.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_unit_luas_bangunan_unit_luas_tanah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='jenis_bangunan',
            field=models.CharField(blank=True, choices=[('lantai_1', 'Lantai 1'), ('lantai_2', 'Lantai 2')], default=None, max_length=100, null=True, verbose_name='Jenis Bangunan'),
        ),
    ]
