# Generated by Django 6.0.6 on 2026-09-05 03:32 — disaring manual.
# Catatan: AlterField tax_amount (6 line model) TIDAK disertakan — drift
# pra-existing dari refactor pajak (d267f1b), di luar scope task project.unit.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_unit_jenis_bangunan'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='harga_bangunan_l1_m2',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Harga bangunan per m² untuk unit Lantai 1', max_digits=18, null=True, verbose_name='Harga Bangunan L1 Per m²'),
        ),
        migrations.AddField(
            model_name='project',
            name='harga_bangunan_l2_m2',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Harga bangunan per m² untuk unit Lantai 2', max_digits=18, null=True, verbose_name='Harga Bangunan L2 Per m²'),
        ),
        migrations.AddField(
            model_name='project',
            name='harga_tanah_m2',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Harga tanah per m² — dipakai menghitung Harga Jual Dasar Unit Tersedia', max_digits=18, null=True, verbose_name='Harga Tanah Per m²'),
        ),
        migrations.AddField(
            model_name='projectunit',
            name='harga_jual_dasar',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Harga Tanah/m² × Luas Tanah + Harga Bangunan/m² × Luas Bangunan', max_digits=18, null=True, verbose_name='Harga Jual Dasar'),
        ),
        migrations.AddField(
            model_name='projectunit',
            name='jenis_bangunan',
            field=models.CharField(blank=True, choices=[('lantai_1', 'Lantai 1'), ('lantai_2', 'Lantai 2')], default=None, help_text='Otomatis dari master Unit', max_length=100, null=True, verbose_name='Jenis Bangunan'),
        ),
        migrations.AddField(
            model_name='projectunit',
            name='luas_bangunan',
            field=models.FloatField(blank=True, default=None, help_text='Otomatis dari master Unit', null=True, verbose_name='Luas Bangunan (m²)'),
        ),
        migrations.AddField(
            model_name='projectunit',
            name='luas_tanah',
            field=models.FloatField(blank=True, default=None, help_text='Otomatis dari master Unit', null=True, verbose_name='Luas Tanah (m²)'),
        ),
    ]
