# Generated by Django 6.0.6 on 2026-09-05 10:44 — disaring manual.
# Catatan: AlterField tax_amount (6 line model) TIDAK disertakan — drift
# pra-existing dari refactor pajak (d267f1b), di luar scope task Blok.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_project_harga_bangunan_l1_m2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(default=None, help_text='Nama blok / kelompok unit pada proyek', max_length=255, verbose_name='Nama Blok')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.project', verbose_name='Project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Blok',
                'verbose_name_plural': 'Blok',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
