# Generated by Django 6.0.6 on 2026-09-05 23:51 — disaring manual.
# Catatan: AlterField tax_amount (6 line model) TIDAK disertakan — drift
# pra-existing dari refactor pajak (d267f1b), di luar scope task Blok di unit.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectunit',
            name='block_id',
            field=models.ForeignKey(blank=True, help_text='Pilih Blok dari data tab Blok pada header proyek ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.block', verbose_name='Blok'),
        ),
    ]
