# Generated by Django 6.0.6 on 2026-09-08 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_projectunit_block_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreceipt',
            name='difference_account',
            field=models.ForeignKey(blank=True, help_text='Akun tujuan mapping selisih kurang/lebih bayar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.chartofaccount', verbose_name='Akun Selisih (COA)'),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='difference_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Selisih kurang/lebih bayar yang dimapping ke akun COA saat input lewat Proses Pembayaran.', max_digits=18, null=True, verbose_name='Selisih Mapping'),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='difference_account',
            field=models.ForeignKey(blank=True, help_text='Akun tujuan mapping selisih kurang/lebih bayar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.chartofaccount', verbose_name='Akun Selisih (COA)'),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='difference_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Selisih kurang/lebih bayar yang dimapping ke akun COA saat input lewat Proses Pembayaran.', max_digits=18, null=True, verbose_name='Selisih Mapping'),
        ),
    ]
