# Generated by Django 6.0.6 on 2026-09-09 11:43
# DIPRUNING: hanya CreateModel Refund — AlterField tax_amount dkk dari autogen
# dibuang manual (bukan bagian perubahan ini).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_vendorbill_deduct_dp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('refund_date', models.DateField(default=None, verbose_name='Tanggal Refund')),
                ('amount', models.DecimalField(decimal_places=2, default=None, max_digits=18, verbose_name='Nominal Refund')),
                ('notes', models.TextField(blank=True, default=None, null=True, verbose_name='Catatan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer_receipt', models.ForeignKey(blank=True, help_text='Terisi bila refund dari Penerimaan Customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customerreceipt', verbose_name='Dari Penerimaan Customer')),
                ('deposit', models.ForeignKey(blank=True, help_text='Terisi bila refund dari Deposit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.deposit', verbose_name='Dari Deposit')),
                ('payment_method', models.ForeignKey(blank=True, help_text='Kas/bank yang menerima / mengeluarkan refund.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.paymentmethod', verbose_name='Kas/Bank')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('vendor_payment', models.ForeignKey(blank=True, help_text='Terisi bila refund dari Pembayaran Vendor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.vendorpayment', verbose_name='Dari Pembayaran Vendor')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refund',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
