# Generated by Django 6.0.6 on 2026-09-09 11:45
# DIPRUNING: hanya AddField reference Refund — AlterField lain autogen dibuang manual.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_alter_customerinvoice_sales_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='reference',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='No. Refund'),
        ),
    ]
