# Generated by Django 6.0.6 on 2026-09-10 13:11
# Catatan: entri AlterField autogen (tax_amount/deduct_dp/sales_order) dibuang
# manual — migrasi ini hanya menambah tabel RBAC (Role, RoleMenuAccess).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_tax_is_include'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('name', models.CharField(default=None, help_text='Contoh: Admin, Sales, Gudang', max_length=255, verbose_name='Nama Role')),
                ('code', models.CharField(blank=True, default=None, help_text='Identifier singkat, mis. ADMIN, SALES, GUDANG', max_length=255, null=True, verbose_name='Kode')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Keterangan')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleMenuAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('menu_key', models.CharField(default=None, help_text='Key menu/section/modul, mis. /purchase.order', max_length=255, verbose_name='Menu Key')),
                ('menu_type', models.CharField(blank=True, choices=[('module', 'Modul'), ('section', 'Section'), ('menu', 'Menu')], default='menu', max_length=100, null=True, verbose_name='Tipe')),
                ('allow', models.BooleanField(default=True, verbose_name='Allow')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('role_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.role', verbose_name='Role')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Role Menu Access',
                'verbose_name_plural': 'Role Menu Access',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
